- copy:
    src: Dockerfile
    dest: /home/ec2-user/Dockerfile
    owner: ec2-user
    group: ec2-user
    mode: u+rwx,g+rwx

- name : Copy Grafana Config
  template:
    src: defaults.ini.j2
    dest: defaults.ini
    owner: ec2-user
    group: ec2-user
    mode: u+rwx,g+rwx

- name: Install Docker Package
  pip:
    name: docker

- name: Build grafana Image
  docker_image:
      path: .
      name: grafana-image

- name: Run grafana container
  docker_container:
      name: grafana
      image: grafana-image
      ports:
        - "3000:3000"
