- hosts: bitbucket-logstash
  become: yes
  roles:
    - role: docker
    - role: logstash-bitbucket

- hosts: jira-logstash
  become: yes
  roles:
    - role: docker
    - role: logstash-jira

- hosts: jenkins-logstash
  become: yes
  roles:
    - role: docker
    - role: logstash-jenkins
