- name: Copy dockerfile
  copy:
    src: Dockerfile
    dest: /home/ec2-user/Dockerfile
    owner: ec2-user
    group: ec2-user
    mode: u+rwx,g+rwx

- name: Copy Jenkins Pipeline File
  template:
    src: jenkins.yml.j2
    dest: jenkins.yml
    owner: ec2-user
    group: ec2-user
    mode: u+rw,g+rw

- name: Copy Logstash Configuration File
  template:
    src: logstash_conf.yml.j2
    dest: logstash.yml
    owner: ec2-user
    group: ec2-user
    mode: u+rw,g+rw

- name: Install Docker Package
  pip:
    name: docker

- name: Build Logstash Image
  docker_image:
      path: .
      name: liatrio-logstash-jenkins

- name: Run Logstash-Jenkins Container
  docker_container:
      name: logstash-jenkins
      image: liatrio-logstash-jenkins
      ports: 
        - "{{private_interface}}:9000:9000"
