- copy:
    src: Dockerfile
    dest: /home/ec2-user/Dockerfile
    owner: ec2-user
    group: ec2-user
    mode: u+rwx,g+rwx

- name: Build Kibana Image
  shell: docker build -t liatrio-kibana .

- name: Run Kibana container
  shell: docker run -dp 5601:5601 liatrio-kibana
