- copy:
    src: Dockerfile
    dest: /home/ec2-user/Dockerfile
    owner: ec2-user
    group: ec2-user
    mode: u+rwx,g+rwx

- template:
    src: kibana.yml.j2
    dest: kibana.yml
    owner: ec2-user
    group: ec2-user
    mode: u+rw,g+rw

- name: Build Kibana Image
  shell: docker build -t liatrio-kibana .

- name: Run Kibana container
  shell: docker run -dp 5601:5601 --name kibana liatrio-kibana
