- copy:
    src: Dockerfile
    dest: /home/ec2-user/Dockerfile
    owner: ec2-user
    group: ec2-user
    mode: u+rwx,g+rwx

- template:
    src: bitbucket.yml.j2
    dest: bitbucket.yml
    owner: ec2-user
    group: ec2-user
    mode: u+rw,g+rw

- name: Build Logstash Image
  shell: docker build -t liatrio-logstash-bitbucket .

- name: Run Kibana container
  shell: docker run -dp 5044:5044 --name logtash liatrio-logstash-bitbucket
