- copy:
    src: Dockerfile
    dest: /home/ec2-user/Dockerfile
    owner: ec2-user
    group: ec2-user
    mode: u+rwx,g+rwx

- name: Copy Bitbucket
  template:
    src: bitbucket.yml.j2
    dest: bitbucket.yml
    owner: ec2-user
    group: ec2-user
    mode: u+rw,g+rw

- name: Copy Logstash conf
  template:
    src: logstash_conf.yml.j2
    dest: logstash.yml
    owner: ec2-user
    group: ec2-user
    mode: u+rw,g+rw

- name: Build Logstash Image
  docker_image:
      path: .
      name: liatrio-logstash-bitbucket

- name: Run Kibana container
  docker_container:
      name: logstash
      image: liatrio-logstash-bitbucket
